# Generated by Django 4.2 on 2023-06-26 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'code',
                    models.CharField(
                        help_text='Код активации купона',
                        max_length=50,
                        unique=True,
                        verbose_name='код',
                    ),
                ),
                (
                    'valid_since',
                    models.DateTimeField(
                        help_text='Время начала действия купона',
                        verbose_name='активен с',
                    ),
                ),
                (
                    'valid_to',
                    models.DateTimeField(
                        help_text='Время окончания действия купона',
                        verbose_name='активен до',
                    ),
                ),
                (
                    'discount',
                    models.IntegerField(
                        help_text='Скидка в процентах',
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name='скидка',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        help_text='Купон активен или нет',
                        verbose_name='активен',
                    ),
                ),
            ],
        ),
    ]
