# Generated by Django 4.2 on 2023-06-26 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'купон', 'verbose_name_plural': 'купоны'},
        ),
    ]
