# Generated by Django 4.2 on 2023-06-08 22:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True,
                help_text='Описание продукта',
                verbose_name='описание',
            ),
        ),
    ]
