# Generated by Django 4.2 on 2023-06-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Картинка продукта',
                upload_to='products/%Y/%m/%d/%h/%s',
                verbose_name='картинка',
            ),
        ),
    ]
