# Generated by Django 4.2 on 2023-06-09 20:39

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(
                help_text='Слаг имени',
                max_length=200,
                unique=True,
                verbose_name='слаг',
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Картинка продукта',
                upload_to=shop.models.generate_image_path,
                verbose_name='картинка',
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(
                help_text='Слаг для продукта',
                max_length=200,
                unique=True,
                verbose_name='слаг',
            ),
        ),
    ]
