# Generated by Django 4.2 on 2023-06-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0002_rename_created_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
