# Generated by Django 4.2 on 2023-06-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0003_order_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(
                help_text='Электронная почта заказчика',
                max_length=254,
                verbose_name='электронная почта',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='stripe_id',
            field=models.CharField(
                blank=True,
                help_text='Идентификатор платежа в stripe',
                max_length=250,
                verbose_name='идентификатор платежа',
            ),
        ),
    ]
