# Generated by Django 4.2 on 2023-06-26 15:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('coupons', '0002_alter_coupon_options'),
        ('orders', '0004_alter_order_email_alter_order_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(
                blank=True,
                help_text='Купон, применяемый к заказу',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='orders',
                to='coupons.coupon',
                verbose_name='купон',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(
                default=0,
                help_text='Скидка к заказу',
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name='скидка',
            ),
        ),
    ]
